services:
  vine-landing:
    image: vine-landing
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vine-container
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
